version: '3.5'
services:
  jupyter-lab:
    image: $JUPYTER_LAB_IMAGE
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - $JUPYTER_LAB_IMAGE
      args:
        - CADCAD_KEY
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/home/jupyter/workspace
