kind: Namespace
apiVersion: v1
metadata:
  name: jupyter
  labels: 
    name: jupyter
---
# Frontend Deployment (Pod)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-lab
  namespace: jupyter
  labels:
    app: jupyter-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-lab
  # Pod template
  template:
    metadata:
      labels:
        app: jupyter-lab
    spec:
      containers:
        - name: jupyter-lab
          image: registry.gitlab.com/linumlabs/molecule-system-modelling/jupter-lab:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry-molecule
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: jupyter-lab
  namespace: jupyter
  labels:
    app: jupyter-lab
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: jupyter-lab
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jupyter-lab
  namespace: jupyter
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: 1200
    nginx.ingress.kubernetes.io/proxy-send-timeout: 1200
spec:
  rules:
    - host: lab.mol.ai
      http:
        paths:
          - backend:
              serviceName: jupyter-lab
              servicePort: 80
            path: /